[package]
name = "node"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libm = "^0.2.5"
nalgebra = "^0.31"
dyn-clone = "^1.0.9"
rand = "^0.8.5"
csv = "1.1"
